# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{vj-player-sdk}
  s.version = "0.4.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["sixones", "danski"]
  s.date = %q{2009-10-30}
  s.default_executable = %q{playersdk}
  s.description = %q{Videojuicer Player SDK runtime and compiler to create and build Player Addons.}
  s.email = %q{adam@videojuicer.com}
  s.executables = ["playersdk"]
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    ".gitignore",
     "README.textile",
     "Rakefile",
     "VERSION.yml",
     "bin/playersdk",
     "lib/playersdk.rb",
     "lib/playersdk/compiler.rb",
     "lib/playersdk/compilers/flex.rb",
     "lib/playersdk/core_ext/hash.rb"
  ]
  s.homepage = %q{http://videojuicer.com/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Videojuicer Player SDK runtime and compiler to create and build Player Addons.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<open4>, [">= 0.9.6"])
      s.add_runtime_dependency(%q<rubyzip>, [">= 0.9.1"])
    else
      s.add_dependency(%q<open4>, [">= 0.9.6"])
      s.add_dependency(%q<rubyzip>, [">= 0.9.1"])
    end
  else
    s.add_dependency(%q<open4>, [">= 0.9.6"])
    s.add_dependency(%q<rubyzip>, [">= 0.9.1"])
  end
end

